name: Build .zip File

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch: # Run manually

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set environment variables
        id: repo-name
        shell: bash
        run: |
          echo "value=`basename ${{ github.repository }}`" >> $GITHUB_OUTPUT

      - name: Zip Data Pack
        run: zip -r ${{ github.workspace }}/${{ steps.repo-name.outputs.value }}-${{ github.ref_name }}.zip .
        working-directory: ${{ github.workspace }}

      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ steps.repo-name.outputs.value }}-*.zip
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body: ${{ github.event.head_commit.message }}
